FROM baseimage

# Set your service name on this line
ENV SERVICE_NAME

ENV BASE_PATH $SVC_PATH/$SERVICE_NAME/
ADD . $BASE_PATH
RUN mkdir $BASE_PATH/logs
WORKDIR $BASE_PATH

ENTRYPOINT $BASE_PATH/entrypoint.sh
