FROM baseimage

# SET SERVICE NAME HERE
ENV SERVICE_NAME = EXAMPLE_SERVICE

ENV BASE_PATH $SVC_PATH/$SERVICE_NAME/
ADD . $BASE_PATH
WORKDIR $BASE_PATH

# ============= Dependencies ============= #

# INSTALL NON-REQUIREMENTS.TXT DEPENDENCIES HERE

# install pypi dependencies
ADD ./requirements.txt $BASE_PATH/requirements.txt
RUN pip install -r requirements.txt

# ============= Source Code ============= #

ADD . $BASE_PATH
RUN pip install .

ENTRYPOINT $BASE_PATH/entrypoint.sh
